### ISSUE TITLE
Tech: Implement Login with Near Account

### ISSUE THREAD

**Issue by MohamadSafi** [HaidarJbeily7/YieldGuard#19]
**Description**: Implement login page use Near Account for Authntication
**Tasks**:

- [x] Create Login Page with Near Auth
- [x] Implement Protected Routes
- [x] create User Store
